//************************************************************************************
//**  
//**  Source name:   C:\Users\personpc\Documents\GitHub\denem-flow\Flowcode1.fcfx
//**  Title:         
//**  Description:   
//**  Device:        PIC.18F.18F25K80
//**  
//**  Generated by:  Flowcode v7.2.1.4
//**  Date:          Monday, December 11, 2017 11:29:57
//**  Users:         1
//**  Registered to: sezgin ozan
//**  Licence key:   4AEKU2
//**  
//**  
//**  http://www.matrixtsl.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_CAL_PIC

#define MX_CLK_SPEED 19660800

#define FCP_NULL Unconnected_Port



#include <xc.h>
#include <math.h>

__PROG_CONFIG(0x1, 0xF2BF);
__PROG_CONFIG(0x2, 0x74FF);
__PROG_CONFIG(0x3, 0xFFFF);
__PROG_CONFIG(0x4, 0xFFFF);
__PROG_CONFIG(0x5, 0xFFFF);
__PROG_CONFIG(0x6, 0xFFFF);
__PROG_CONFIG(0x7, 0xFFFF);

/*========================================================================*\
   Use :Include the type definitions
\*========================================================================*/
#include "C:\Program Files (x86)\Flowcode 7\CAL\internals.c"





/*========================================================================*\
   Use :panel
       :Variable declarations
       :Macro function declarations
\*========================================================================*/
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_GLOBAL MX_UINT8 FCV_AHMET = (0x8);


/*========================================================================*\
   Use :Include the chip adaption layer
\*========================================================================*/
#include "C:\Program Files (x86)\Flowcode 7\CAL\includes.c"


/*========================================================================*\
   Use :panel
       :Macro implementations
\*========================================================================*/


/*========================================================================*\
   Use :Ana
\*========================================================================*/
void main()
{
ANCON0 = 0x00;
ANCON1 = 0x00;




	// Gecikme
	// Gecikme: 1 ms
	FCI_DELAYBYTE_MS(1);

	// ahmet
	// Karar: 0?
	if (0)
	{

		// Ç?kt?
		// Ç?kt?: 0 -> A1
		FCP_SET(B, A, 0x02, 1, (0));
	} else {

		// Ç?kt?
		// Ç?kt?: 1 -> A1
		FCP_SET(B, A, 0x02, 1, (1));
	}

	mainendloop: goto mainendloop;
}



/*========================================================================*\
   Use :Kesme
\*========================================================================*/
void MX_INTERRUPT_MACRO(void)
{

}




